name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  # Lint:
    # Lint 任务
  UnitTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: npm/action-setup@v2.1.0
      with:
        version: 7.2.1
    - name: Install modules
      run: npm install
    - name: Run Test
      run: npm run test:run
    
